version: '3.9'

services:
  postgres:
    hostname: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    healthcheck:
      test: ["CMD", "psql", "-U", "${POSTGRES_USER}", "${POSTGRES_DB}"]
    ports:
      - '5432:5432'
    networks:
      - platform-network

  hive-metastore:
    build:
      context: ./containers/hive-metastore/
      dockerfile: hive-metastore.dockerfile
    hostname: hive-metastore
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=${POSTGRES_DB}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_ENDPOINT_URL=http://minio:9000
    ports:
      - '9083:9083'
    networks:
      - platform-network
  
  trino:
    hostname: trino
    image: 'trinodb/trino:latest'
    ports:
      - '8080:8080'
    volumes:
      - ${PWD}/mnt/trino-etc:/etc/trino
    networks:
      - platform-network
  
  minio:
    hostname: minio
    image: 'quay.io/minio/minio:latest'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    networks:
      - platform-network

volumes:
  minio-data:
    driver: local
  hive-data:
    driver: local

networks:
  platform-network:
    driver: bridge
